POST http://localhost:2525/imposters

{
  "port": 4551,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "and": [
            {
              "equals": {
                "method": "POST",
                "path": "/api/login"
              }
            },
            {
              "equals": {
                "headers": {
                  "Content-Type": "application/json"
                }
              }
            },
            {
              "deepEquals": {
                "body": {
                  "username": "admin",
                  "password": "secret"
                }
              }
            }
          ]
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 200,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "status": "ok",
              "token": "validtoken"
            }
          }
        }
      ]
    },
    {
      "predicates": [
        {
          "and": [
            {
              "equals": {
                "method": "POST",
                "path": "/api/login"
              }
            },
            {
              "equals": {
                "headers": {
                  "Content-Type": "application/json"
                }
              }
            }
          ]
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 401,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "invalid_credentials"
            }
          }
        }
      ]
    }
  ]
}
