POST http://localhost:2525/imposters

{
  "port": 4548,
  "protocol": "http",
  "stubs": [{
    "responses": [
      {"is": { "statusCode": 400 }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/ex0",
            "method": "POST "
          }
        }
      ]
    }]
  }]
}

